CREATE TABLE `license_company` (
  `license_company_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `customer_company_id` int(10) unsigned DEFAULT NULL COMMENT 'Asociado a la empresa dueña de la licencia.',
  `license_type_id` int(10) unsigned DEFAULT NULL COMMENT 'Asociado a la tabla que indica los tipos de licencia disponibles (license_type)',
  `pay_element_id` int(10) unsigned DEFAULT NULL COMMENT 'Asocia el medio de pago de la licencia. Llave foránea de pay_element.',
  `customer_user_id` int(10) unsigned DEFAULT NULL COMMENT 'usuario que creó la licencia',
  `instance_name` varchar(60) CHARACTER SET utf8 DEFAULT NULL COMMENT 'Nombre de la licencia.',
  `expr_date` datetime DEFAULT NULL COMMENT 'Fecha de término de la licencia.',
  `auto_renew` tinyint(1) DEFAULT NULL COMMENT 'Idica si tiene la opción de autorenovación de licencia. 1= si, 0 =No',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creación del registro.',
  `modification_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de ultima modificación del registro.',
  `last_pay_date` datetime DEFAULT NULL COMMENT 'Última fecha de pago registrada.',
  `status` int(11) DEFAULT NULL COMMENT 'Permite eliminar de manera lógica un registro, sin borrar la información dese la bd.',
  `cdkey` text COLLATE utf8_spanish_ci,
  `pkey` text COLLATE utf8_spanish_ci,
  `retries` int(11) DEFAULT NULL,
  `salt` varchar(64) COLLATE utf8_spanish_ci DEFAULT NULL,
  PRIMARY KEY (`license_company_id`),
  KEY `fk_cco_lco_id_idx` (`customer_company_id`),
  KEY `fk_lty_lco_id_idx` (`license_type_id`),
  KEY `fk_pel_lco_id_idx` (`pay_element_id`),
  KEY `idx_expiration` (`expr_date`,`status`) USING BTREE,
  CONSTRAINT `fk_cco_lco_id` FOREIGN KEY (`customer_company_id`) REFERENCES `customer_company` (`customer_company_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_lty_lco_id` FOREIGN KEY (`license_type_id`) REFERENCES `license_type` (`license_type_id`),
  CONSTRAINT `fk_pel_lco_id` FOREIGN KEY (`pay_element_id`) REFERENCES `pay_element` (`pay_element_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Incluye las licencias individales adqueridas por cada empresa.'