CREATE TABLE `customer_user` (
  `customer_user_id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Llave autoincremental',
  `customer_company_id` int(10) unsigned DEFAULT NULL COMMENT 'Llave foránea a la tabla customer_company. Indica la compañía a la cual pertenece el usuario registrado.',
  `email` varchar(250) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Identificador único del usuario. Un mismo e-mail no puede tener mas de un usuario.',
  `name` varchar(100) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'Nombre del usuario.',
  `id_document` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL COMMENT 'Número de identificación o DNI (documento nacional de identificación). En el caso chileno sería el número de RUN.',
  `country_id` int(10) unsigned DEFAULT '1' COMMENT 'Llave foránea con el id de país.',
  `pass_curr` varchar(60) CHARACTER SET utf8 NOT NULL COMMENT 'Password actual, codificada.',
  `pass_prev` varchar(60) CHARACTER SET utf8 DEFAULT NULL COMMENT 'Penúltima contraseña, codificada.',
  `pass_prev2` varchar(60) CHARACTER SET utf8 DEFAULT NULL COMMENT 'Ante-penúltima contraseña, codificada.',
  `pass_expr_date` datetime DEFAULT NULL COMMENT 'Fecha de expiración de contraseña.',
  `validation_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT 'Estado de validación de la cuenta (correo).',
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creación del usuario.',
  `modification_date` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de última modificación del usuario.',
  `status` tinyint(1) DEFAULT '1' COMMENT 'Permite eliminar lógicamente una cuenta, sin eliminar la información.',
  `language_list_id` int(10) unsigned DEFAULT '1' COMMENT 'Apunta a la tabla laguage_list. Indica el idioma preferido por el usuario para ver el portal.',
  `validate_access` tinyint(4) DEFAULT '1' COMMENT 'Valor para bloquear el acceso a la cuenta después de los 3 intentos fallidos',
  PRIMARY KEY (`customer_user_id`),
  UNIQUE KEY `email_unique` (`email`),
  KEY `fk_cco_cus_id_idx` (`customer_company_id`),
  KEY `fk_ctr_cus_id_idx` (`country_id`),
  CONSTRAINT `fk_cco_cus_id` FOREIGN KEY (`customer_company_id`) REFERENCES `customer_company` (`customer_company_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_ctr_cus_id` FOREIGN KEY (`country_id`) REFERENCES `country` (`country_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=185 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Contempla a todos los usuarios de todos los productos ofrecidos por dPa'